Common:
  Results: Results/
  Metrics:
    Name: P@10, R@10, NDCG@10
    CachePath: metrics/
  DataSet:
    Name: m-bier
    Path: !ENV ${DATASET_PATH} # Update the dataset path here or add DATASET_PATH to environment.
    Train: '' # Set <>% or <> exact number of batches to train
    Test: '' # Set <>% or <> exact number of batches to test

FineTuning:
  Action: False
  Model:
    Name: # Name of the model
    CachePath : model/
    OutputPath: tuned-model/
    Index: -1
    LoadCheckPoint: False
    CheckPointIndex: -1
  Hyperparameters:
    TrainBatchSize: 8
    EvalBatchSize: 32
    Epochs: 1
    Lr: 0.00005
    WeightDecay: 0.3
    WarmUpRatio: 0.03
    Steps:
      SaveSteps: 1000
      EvalSteps: 1000
      LoggingSteps: 100
      GradientAccumulation: 1

Evaluate:
  Action: False
  Model:
    UseLocal: False
    Name: # Name of the model
    CachePath: model/
    Index: -1
    LoadCheckPoint: False
    CheckPointIndex: -1
  Hyperparameters:
     EvalBatchSize: 32