Common:
  Results: Results/
  Metrics:
    Name: R@5, R@10, NDCG@10
    CachePath: metrics/
  DataSet:
    Name: MBIER
    QueryInstructionsPath: datasetUtils/query_instructions.tsv
    Path: !ENV ${DATASET_PATH} # Update the dataset path here or add DATASET_PATH to environment.
    FilterDomains:
      - visualnews
      - fashion200k
      - mscoco
    Train: '' # Set <>% or <> exact number of batches to train
    Test: '' # Set <>% or <> exact number of batches to test
    Candidate: '' # Set <>% or <> exact number of batches for candidate

FineTuning:
  Action: False
  NegativeCandidates:
    UseModalityNegatives: True
    ModalityNegativesPath: datasetUtils/dummy.json # file path
    IncludeCrossDomainNegatives: False
    CandidateSize: 3
  Model:
    UseLocal: False
    Name: openai/clip-vit-large-patch14
    CachePath : model/
    OutputPath: tuned-model/
    Index: -1
    LoadCheckPoint: False
    CheckPointIndex: -1
  Hyperparameters:
    UseCPU: False
    TrainBatchSize: 16
    EvalBatchSize: 32
    Epochs: 5
    Lr: 0.00001
    WeightDecay: 0.2
    WarmUpRatio: 0.05
    Steps:
      SaveSteps: 200
      EvalSteps: 100
      LoggingSteps: 100
      GradientAccumulation: 1

Evaluate:
  Action: False
  Model:
    UseLocal: False
    Name: openai/clip-vit-large-patch14 # Name of the model
    CachePath: model/
    Index: -1
    LoadCheckPoint: False
    CheckPointIndex: -1
  Hyperparameters:
     EvalBatchSize: 32

Retrieval:
  Action: False
  Model:
    Name: openai/clip-vit-large-patch14
    Index: -1
  BatchSize: 128
  Top: 10